In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['d'] = 6

In [11]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [12]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [13]:
'b' in obj2


True

In [14]:
6 in obj2

False

In [15]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000,'Utah': 5000}

In [16]:
obj3 = pd.Series(sdata)

In [17]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [18]:
obj4 = pd.Series(sdata,states)

In [19]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [20]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [21]:
obj4.name = 'population'

In [22]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [23]:
obj4.index.name = 'state'

In [24]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada','Nevada'],'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [25]:
data

{'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2],
 'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003]}

In [26]:
frame = pd.DataFrame(data)

In [27]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [28]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [29]:
frame2 = pd.DataFrame(data,columns = ['year','state','pop','debt'],index = ['one', 'two', 'three', 'four','five', 'six'])

In [30]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [31]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [32]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [33]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [34]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four','five'])

In [35]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [36]:
frame2.debt = val

In [37]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [38]:
frame2['eastern'] = frame2.state == 'Ohio'

In [39]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [40]:
del frame2['eastern']

In [41]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [42]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [43]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [44]:
frame3 = pd.DataFrame(pop, index = [2000,2001,2002])

In [45]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [46]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64')

In [47]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [48]:
frame3 = pd.DataFrame(pop,index = [2000,2001,2002])

In [49]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [50]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}

In [51]:
pdata

{'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64, 'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64}

In [52]:
pd.DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [53]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [54]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [55]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [56]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [57]:
obj1 = pd.Series([1,2,3])

In [58]:
obj1

0    1
1    2
2    3
dtype: int64

In [59]:
obj

a    0
b    1
c    2
dtype: int64

In [60]:
index = obj.index

In [61]:
index

Index(['a', 'b', 'c'], dtype='object')

In [62]:
index[1]

'b'

In [63]:
index[1:]

Index(['b', 'c'], dtype='object')

In [64]:
import numpy as np
labels = pd.Index(np.arange(3))

In [65]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [66]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [67]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [68]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [69]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [70]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64', name='year')

In [71]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a','c'])

In [72]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [73]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [74]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2,4])

In [75]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [76]:
obj3.reindex(range(6),method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [77]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),index=['a', 'c', 'd'],columns=['Ohio', 'Texas','California'])

In [78]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [79]:
frame2 = frame.reindex(['a','b','c','d'])

In [80]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [81]:
states = ['Texas', 'Utah', 'California']

In [82]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [83]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd','e'])

In [84]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [85]:
new_obj = obj.drop('c')

In [86]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [87]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [88]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [89]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'NewYork'], columns=['one', 'two', 'three','four'])

In [90]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [91]:
data.drop(['one','two'],axis = 1)

three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
NewYork      14    15

In [92]:
data.drop(['Ohio','Utah'])

one  two  three  four
Colorado    4    5      6     7
NewYork    12   13     14    15

In [93]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [94]:
obj.drop('c',inplace = True)

In [95]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [96]:
a = np.arange(15)

In [97]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [98]:
a1 = a.reshape(3,5)

In [99]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [100]:
a1[1]

array([5, 6, 7, 8, 9])

In [101]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [102]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [103]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [104]:
obj['b']

1.0

In [105]:
obj[1]

1.0

In [106]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [107]:
obj[:2]

a    0.0
b    1.0
dtype: float64

In [108]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [109]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [110]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [111]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'NewYork'],columns=['one', 'two', 'three','four'])

In [112]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [113]:
data['two']

Ohio         1
Colorado     5
Utah         9
NewYork     13
Name: two, dtype: int32

In [114]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [115]:
data[:]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [116]:
data[['one','two']]

one  two
Ohio        0    1
Colorado    4    5
Utah        8    9
NewYork    12   13

In [117]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [118]:
data[:1]

one  two  three  four
Ohio    0    1      2     3

In [119]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [120]:
data[1:2]

one  two  three  four
Colorado    4    5      6     7

In [121]:
data[data['one']<4]

one  two  three  four
Ohio    0    1      2     3

In [122]:
data['one']

Ohio         0
Colorado     4
Utah         8
NewYork     12
Name: one, dtype: int32

In [123]:
data[1:2]

one  two  three  four
Colorado    4    5      6     7

In [124]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
NewYork   False  False  False  False

In [125]:
data[data<5]=0

In [126]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [127]:
data.loc[['Ohio','Utah'],['one','two']]

one  two
Ohio    0    0
Utah    8    9

In [128]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [129]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [130]:
list(data.iloc[2])

[8, 9, 10, 11]

In [131]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [132]:
data.iloc[:, :3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
NewYork    12   13     14

In [133]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
NewYork    12   13     14

In [134]:
data.iloc[:][data.three>5]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [135]:
ser = pd.Series(np.arange(3))

In [136]:
ser

0    0
1    1
2    2
dtype: int32

In [137]:
ser[1]

1

In [138]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [139]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [140]:
ser2[-1]

2.0

In [141]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd','e'])

In [142]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [143]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a', 'c', 'e', 'f', 'g'])

In [144]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [145]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [146]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)),columns=list('bcd'),index=['Ohio', 'Texas', 'Colorado'])

In [147]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [148]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)),columns=list('bde'),index=['Utah', 'Ohio', 'Texas','Oregon'])

In [149]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [150]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [151]:
df1 = pd.DataFrame({'A': [1, 2]})

In [152]:
df1

A
0  1
1  2

In [153]:
df2 = pd.DataFrame({'B': [3, 4]})

In [154]:
df2

B
0  3
1  4

In [155]:
df1+df2

A   B
0 NaN NaN
1 NaN NaN

In [156]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),columns=list('abcd'))

In [157]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns=list('abcde'))

In [158]:
df2.loc[1,'c']=np.nan

In [159]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   NaN   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [160]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0   NaN  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [161]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0   6.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [162]:
df3 = df1+df2

In [163]:
df3.fillna(0)

a     b     c     d    e
0   0.0   2.0   4.0   6.0  0.0
1   9.0  11.0   0.0  15.0  0.0
2  18.0  20.0  22.0  24.0  0.0
3   0.0   0.0   0.0   0.0  0.0

In [164]:
1/df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [165]:
df1.reindex(columns = df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [166]:
arr = np.arange(12).reshape(3,4)

In [167]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [168]:
arr[0]

array([0, 1, 2, 3])

In [169]:
arr-arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [170]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),columns=list('bde'),index=['Utah', 'Ohio', 'Texas','Oregon'])

In [171]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [172]:
series = frame.iloc[0]

In [173]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [174]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [175]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [176]:
series2

b    0
e    1
f    2
dtype: int64

In [177]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [178]:
series3 = frame['d']

In [179]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [180]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [181]:
frame.sub(series3,axis = 'index') #匹配到列做减法

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [182]:
frame = pd.DataFrame(np.random.randn(4, 3),columns=list('bde'),index=['Utah', 'Ohio', 'Texas','Oregon'])

In [183]:
frame

b         d         e
Utah   -0.053876  0.713722  1.166703
Ohio   -0.144270 -0.219186 -1.326685
Texas  -0.355642  0.144744  0.773465
Oregon -1.286375  0.708073  1.613432

In [184]:
np.abs(frame)

b         d         e
Utah    0.053876  0.713722  1.166703
Ohio    0.144270  0.219186  1.326685
Texas   0.355642  0.144744  0.773465
Oregon  1.286375  0.708073  1.613432

In [185]:
f = lambda x: x.max() - x.min()

In [186]:
f

<function __main__.<lambda>>

In [187]:
frame.apply(f)

b    1.232500
d    0.932908
e    2.940118
dtype: float64

In [188]:
frame

b         d         e
Utah   -0.053876  0.713722  1.166703
Ohio   -0.144270 -0.219186 -1.326685
Texas  -0.355642  0.144744  0.773465
Oregon -1.286375  0.708073  1.613432

In [189]:
frame.apply(f, axis='columns')

Utah      1.220578
Ohio      1.182415
Texas     1.129106
Oregon    2.899808
dtype: float64

In [190]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

In [191]:
frame.apply(f)

b         d         e
min -1.286375 -0.219186 -1.326685
max -0.053876  0.713722  1.613432

In [192]:
format = lambda x:'%.2f'%x

In [193]:
frame.applymap(format)

b      d      e
Utah    -0.05   0.71   1.17
Ohio    -0.14  -0.22  -1.33
Texas   -0.36   0.14   0.77
Oregon  -1.29   0.71   1.61

In [194]:
frame['e'].map(format)

Utah       1.17
Ohio      -1.33
Texas      0.77
Oregon     1.61
Name: e, dtype: object

In [195]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [196]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [197]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [198]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),index=['three', 'one'],columns=['d', 'a', 'b', 'c'])

In [199]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [200]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [201]:
frame.sort_index(1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [202]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [203]:
obj = pd.Series([4, 7, -3, 2])

In [204]:
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [205]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [206]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [207]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [208]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [209]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0,1]})

In [210]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [211]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [212]:
frame.sort_values(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [213]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [214]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [215]:
obj.sort_values()

1   -5
5    0
4    2
3    4
6    4
0    7
2    7
dtype: int64

In [216]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [217]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [218]:
obj.rank(ascending = False,method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [219]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [220]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0,1], 'c': [-2, 5, 8, -2.5]})

In [221]:
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [222]:
frame.rank(axis = 'columns')

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

In [223]:
frame.columns

Index(['a', 'b', 'c'], dtype='object')

In [224]:
frame.rank()

a    b    c
0  1.5  3.0  2.0
1  3.5  4.0  3.0
2  1.5  1.0  4.0
3  3.5  2.0  1.0

In [225]:
frame.index

RangeIndex(start=0, stop=4, step=1)

In [226]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [227]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [228]:
obj.index.is_unique

False

In [229]:
obj['a']

a    0
a    1
dtype: int64

In [230]:
obj['b']

b    2
b    3
dtype: int64

In [231]:
obj['c']

4

In [232]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a','b', 'b'])

In [233]:
df

0         1         2
a -0.101350 -0.360427  1.031683
a  0.746717 -1.388318 -0.125717
b  1.142580 -0.827556 -2.495334
b  0.030496 -1.393764 -0.032580

In [234]:
df.loc['b']

0         1         2
b  1.142580 -0.827556 -2.495334
b  0.030496 -1.393764 -0.032580

In [235]:
df.iloc[1]

0    0.746717
1   -1.388318
2   -0.125717
Name: a, dtype: float64

In [236]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],[np.nan, np.nan], [0.75, -1.3]],index=['a', 'b', 'c', 'd'],columns=['one', 'two'])

In [237]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [238]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [239]:
df.sum(axis = 1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [240]:
np.NaN

nan

In [241]:
np.nan

nan

In [242]:
df.mean(axis=1,skipna= False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [243]:
df.idxmax()

one    b
two    d
dtype: object

In [244]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [245]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [246]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [247]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [248]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [249]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [256]:
price = pd.read_pickle('examples/yahoo_price.pkl')
volume = pd.read_pickle('examples/yahoo_volume.pkl')

In [257]:
returns = price.pct_change()

In [258]:
price

AAPL        GOOG         IBM       MSFT
Date                                                     
2010-01-04   27.990226  313.062468  113.304536  25.884104
2010-01-05   28.038618  311.683844  111.935822  25.892466
2010-01-06   27.592626  303.826685  111.208683  25.733566
2010-01-07   27.541619  296.753749  110.823732  25.465944
2010-01-08   27.724725  300.709808  111.935822  25.641571
2010-01-11   27.480148  300.255255  110.763844  25.315406
2010-01-12   27.167562  294.945572  111.644958  25.148142
2010-01-13   27.550775  293.252243  111.405433  25.382312
2010-01-14   27.391211  294.630868  113.184773  25.892466
2010-01-15   26.933449  289.710772  112.731385  25.808835
2010-01-19   28.124939  293.516976  114.750251  26.009552
2010-01-20   27.692027  289.915587  111.422546  25.583028
2010-01-21   27.213337  291.199286  110.353231  25.097963
2010-01-22   25.863592  274.730736  107.359151  24.219826
2010-01-25   26.559391  269.730740  107.889534  24.520902
2010-01-26   26.934757  270.939526  107.573014  24.671439
2010-01-27   27.188489  270.779695  108.069178  24.813614
2010-01-28   26.065007  266.878565  105.862111  24.387091
2010-01-29   25.119401  264.705742  104.698697  23.567497
2010-02-01   25.468608  266.244198  106.649125  23.759851
2010-02-02   25.616400  265.295156  107.384814  23.801666
2010-02-03   26.057159  270.140309  107.496027  23.943840
2010-02-04   25.118093  263.127321  105.220523  23.283148
2010-02-05   25.564084  265.380075  105.665355  23.433686
2010-02-08   25.388826  266.468996  104.728745  23.182789
2010-02-09   25.659561  267.952522  105.871586  23.425323
2010-02-10   25.519617  266.958496  105.527873  23.408596
2010-02-11   25.983917  267.932539  106.318414  23.517319
2010-02-12   26.207567  266.294170  106.550416  23.358417
2010-02-16   26.602551  270.380071  107.607330  23.820544
...                ...         ...         ...        ...
2016-09-12  105.440002  769.020020  158.289993  57.049999
2016-09-13  107.949997  759.690002  155.809998  56.529999
2016-09-14  111.769997  762.489990  154.050003  56.259998
2016-09-15  115.570000  771.760010  155.660004  57.189999
2016-09-16  114.919998  768.880005  153.839996  57.250000
2016-09-19  113.580002  765.700012  154.869995  56.930000
2016-09-20  113.570000  771.409973  154.449997  56.810001
2016-09-21  113.550003  776.219971  155.529999  57.759998
2016-09-22  114.620003  787.210022  156.110001  57.820000
2016-09-23  112.709999  786.900024  154.979996  57.430000
2016-09-26  112.879997  774.210022  153.979996  56.900002
2016-09-27  113.089996  783.010010  156.770004  57.950001
2016-09-28  113.949997  781.559998  158.289993  58.029999
2016-09-29  112.180000  775.010010  158.110001  57.400002
2016-09-30  113.050003  777.289978  158.850006  57.599998
2016-10-03  112.519997  772.559998  157.610001  57.419998
2016-10-04  113.000000  776.429993  156.460007  57.240002
2016-10-05  113.050003  776.469971  157.080002  57.639999
2016-10-06  113.889999  776.859985  156.880005  57.740002
2016-10-07  114.059998  775.080017  155.669998  57.799999
2016-10-10  116.050003  785.940002  157.020004  58.040001
2016-10-11  116.300003  783.070007  154.789993  57.189999
2016-10-12  117.339996  786.140015  154.289993  57.110001
2016-10-13  116.980003  778.190002  153.720001  56.919998
2016-10-14  117.629997  778.530029  154.449997  57.419998
2016-10-17  117.550003  779.960022  154.770004  57.220001
2016-10-18  117.470001  795.260010  150.720001  57.660000
2016-10-19  117.120003  801.500000  151.259995  57.529999
2016-10-20  117.059998  796.969971  151.520004  57.250000
2016-10-21  116.599998  799.369995  149.630005  59.660000

[1714 rows x 4 columns]

In [259]:
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [261]:
returns

AAPL      GOOG       IBM      MSFT
Date                                              
2010-01-04       NaN       NaN       NaN       NaN
2010-01-05  0.001729 -0.004404 -0.012080  0.000323
2010-01-06 -0.015906 -0.025209 -0.006496 -0.006137
2010-01-07 -0.001849 -0.023280 -0.003462 -0.010400
2010-01-08  0.006648  0.013331  0.010035  0.006897
2010-01-11 -0.008822 -0.001512 -0.010470 -0.012720
2010-01-12 -0.011375 -0.017684  0.007955 -0.006607
2010-01-13  0.014106 -0.005741 -0.002145  0.009312
2010-01-14 -0.005792  0.004701  0.015972  0.020099
2010-01-15 -0.016712 -0.016699 -0.004006 -0.003230
2010-01-19  0.044238  0.013138  0.017909  0.007777
2010-01-20 -0.015392 -0.012270 -0.029000 -0.016399
2010-01-21 -0.017286  0.004428 -0.009597 -0.018960
2010-01-22 -0.049599 -0.056554 -0.027132 -0.034988
2010-01-25  0.026903 -0.018200  0.004940  0.012431
2010-01-26  0.014133  0.004481 -0.002934  0.006139
2010-01-27  0.009420 -0.000590  0.004612  0.005763
2010-01-28 -0.041322 -0.014407 -0.020423 -0.017189
2010-01-29 -0.036279 -0.008142 -0.010990 -0.033608
2010-02-01  0.013902  0.005812  0.018629  0.008162
2010-02-02  0.005803 -0.003565  0.006898  0.001760
2010-02-03  0.017206  0.018263  0.001036  0.005973
2010-02-04 -0.036039 -0.025961 -0.021168 -0.027593
2010-02-05  0.017756  0.008561  0.004228  0.006466
2010-02-08 -0.006856  0.004103 -0.008864 -0.010707
2010-02-09  0.010664  0.005567  0.010912  0.010462
2010-02-10 -0.005454 -0.003710 -0.003247 -0.000714
2010-02-11  0.018194  0.003649  0.007491  0.004645
2010-02-12  0.008607 -0.006115  0.002182 -0.006757
2010-02-16  0.015071  0.015344  0.009919  0.019784
...              ...       ...       ...       ...
2016-09-12  0.022399  0.012321  0.016700  0.014944
2016-09-13  0.023805 -0.012132 -0.015667 -0.009115
2016-09-14  0.035387  0.003686 -0.011296 -0.004776
2016-09-15  0.033998  0.012158  0.010451  0.016530
2016-09-16 -0.005624 -0.003732 -0.011692  0.001049
2016-09-19 -0.011660 -0.004136  0.006695 -0.005590
2016-09-20 -0.000088  0.007457 -0.002712 -0.002108
2016-09-21 -0.000176  0.006235  0.006993  0.016722
2016-09-22  0.009423  0.014158  0.003729  0.001039
2016-09-23 -0.016664 -0.000394 -0.007239 -0.006745
2016-09-26  0.001508 -0.016127 -0.006452 -0.009229
2016-09-27  0.001860  0.011366  0.018119  0.018453
2016-09-28  0.007605 -0.001852  0.009696  0.001380
2016-09-29 -0.015533 -0.008381 -0.001137 -0.010856
2016-09-30  0.007755  0.002942  0.004680  0.003484
2016-10-03 -0.004688 -0.006085 -0.007806 -0.003125
2016-10-04  0.004266  0.005009 -0.007296 -0.003135
2016-10-05  0.000443  0.000051  0.003963  0.006988
2016-10-06  0.007430  0.000502 -0.001273  0.001735
2016-10-07  0.001493 -0.002291 -0.007713  0.001039
2016-10-10  0.017447  0.014011  0.008672  0.004152
2016-10-11  0.002154 -0.003652 -0.014202 -0.014645
2016-10-12  0.008942  0.003920 -0.003230 -0.001399
2016-10-13 -0.003068 -0.010113 -0.003694 -0.003327
2016-10-14  0.005556  0.000437  0.004749  0.008784
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

[1714 rows x 4 columns]

In [264]:
returns['MSFT'].corr(returns['IBM'])

0.4997636114415114

In [265]:
returns['MSFT'].cov(returns['IBM'])

8.870655479703546e-05

In [266]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [267]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [268]:
returns.corrwith(returns.IBM)

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [269]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

In [272]:
returns.corrwith(volume,axis = 'columns')

Date
2010-01-04         NaN
2010-01-05    0.737298
2010-01-06    0.017069
2010-01-07    0.507614
2010-01-08   -0.779646
2010-01-11   -0.351354
2010-01-12   -0.288724
2010-01-13    0.886307
2010-01-14   -0.492649
2010-01-15   -0.290109
2010-01-19    0.903163
2010-01-20    0.281621
2010-01-21   -0.695922
2010-01-22   -0.247548
2010-01-25    0.801969
2010-01-26    0.866164
2010-01-27    0.793834
2010-01-28   -0.903428
2010-01-29   -0.965129
2010-02-01    0.102765
2010-02-02    0.407264
2010-02-03    0.411436
2010-02-04   -0.943219
2010-02-05    0.890354
2010-02-08   -0.362312
2010-02-09    0.452544
2010-02-10   -0.320394
2010-02-11    0.833547
2010-02-12    0.597530
2010-02-16    0.299554
                ...   
2016-09-12    0.780534
2016-09-13    0.932640
2016-09-14    0.925231
2016-09-15    0.994865
2016-09-16    0.310611
2016-09-19   -0.796153
2016-09-20   -0.331955
2016-09-21    0.089894
2016-09-22   -0.183208
2016-09-23   -0.909847
2016-09-26    0.729212
2016-09-27   -0.232087
2016-0

In [273]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c','c'])

In [274]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [275]:
uniques = obj.unique()

In [276]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [277]:
obj.describe()

count     9
unique    4
top       a
freq      3
dtype: object

In [278]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [279]:
pd.value_counts(obj.values, sort=False)

b    2
c    3
d    1
a    3
dtype: int64

In [280]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [281]:
mask = obj.isin(['b', 'c'])

In [282]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [283]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [284]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [285]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [286]:
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [287]:
unique_vals

0    c
1    b
2    a
dtype: object

In [288]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [289]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],'Qu2': [2, 3, 1, 2, 3],'Qu3': [1, 5, 2, 4, 4]})

In [290]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [293]:
result = data.apply(pd.value_counts).fillna(0)

In [294]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0